package com.cucumber;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
import org.junit.runner.RunWith;
/*
‘@CucumberOptions’ annotation is used to configure the directory that contains the feature files and output plugins.

A JSON report with the name “json:target/cucumber-report.json” will be generated by Cucumber.
It is the input to Cucumber Report generator.

Cucumber automatically reads all directories under the package where it is configured.
*/

@RunWith(Cucumber.class)
@CucumberOptions(features = "classpath:features", plugin = {"pretty", "json:target/cucumber-report.json"})
public class CucumberTest {

}

/*

EXCEPTIONS:
        cucumber.runtime.CucumberException: No backends were found. Please make sure you have a backend module on your CLASSPATH.

*/
